version: 0.2
env:
  parameter-store:
    NPM_TOKEN: "NPM_TOKEN"

phase:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  build:
    commands:
      - npm publish
